{
  "0": "Arcesa asage «Merva Arcynercedjon»",
  "2": "Nyrsesa asage «Gartenlesa Mortata»",
  "6": "Ecresa asage «Ecresa Creten»",
  "8": "Ecresa asage «Yšymela Ecra eas Ardsso Crečyn»",
  "9": "Ecresa asage «Yšymela Ecra eas Mervo Ardsso Crečyn»",
  "10": "Voratesa asage «Vore Lemes»",
  "14": "Čelesa asage «Enpros-Menacesa Cissenata»",
  "16": "Čelesa asage «Gendočelenyl Vorata»",
  "18": "Vore lemes «Denefo Lemys»",
  "20": "Vore lemes «Mja Lemes»",
  "21": "Vore lemes «Fe Lemes»",
  "22": "Vore lemes «*Djulahan Merseda»",
  "26": "Etearesa asage «Merseda Desor Mjoreso Ryl»",
  "28": "Mecrata «Enaldeso Etearyl»",
  "30": "Mecrata «Nesmereso Etearyl»",
  "32": "Gare «Samena Gare»",
  "34": "Gare «Voro Mersedaryl Aso»",
  "36": "Mjoresa asage «Nesmejasartesa Mytratacnata»",
  "38": "Mjoresa nesmeja «Denefamyn Mytra Tacnata»"
}
